#字典类别
##创建字典类别

POST  http://localhost:7001/category/5a6ff7cfde8bc532d85a6c92/update HTTP/1.1
content-type: application/json
Accept: application/json

{
    "code": "T01",
    "name": "用户状态",
    "order": 1
}
